### ISSUE TITLE
Änderungen 1

### ISSUE THREAD

**Issue by marimai** [manuelpuchta/maria-mair.com#2]
<li>Freies<strong> Lektorat </strong>für <a href="http://www.hoffmann-und-campe.de/" target="_blank" rel="noreferrer noopener">Hoffmann und Campe</a></li>

Das möchte ich gerne ändern zu:
**Lektorin** Belletristik und Sachbuch bei [Hoffmann und Campe](url)

Und der Punkt "Korrektorat für den Verlag quayou" bitte ersetzen:
<li><strong>Korrektorat</strong> für verschiedene Agenturen

**Comment by manuelpuchta** [comment]
Hey @marimai, ist up to date: https://maria-mair.com/ :)
